In [1]:
import numpy as np
import datetime

In [2]:
N = 3
EPSILON = 1
J = 3

PAULI_Z = np.array([[1, 0],
                    [0, -1]])
IDENTITY = np.array([[1, 0],
                     [0, 1]])

In [3]:
def n_identities(n: int):
    """Gives a tensor made out of the tensor product on 'n' identity matrices.

    Args:
        n (int): the number of identity matrices

    Returns:
        np.ndarray: the resultant matrix (tensor)
    """
    return np.identity(2**n) if (n > 0) else 1


time = datetime.datetime

In [4]:
# A list to store the operators A
A_ops = []
for i in range(1, N+1):
    # A_i = I (x) I (x) ... (x) sigma^Z (x) ... (x) I (x) I
    #       \-------------/                 \-------------/
    #             i-1                             N-i
    A_i = np.kron(np.kron(n_identities(i-1), PAULI_Z), n_identities(N-i))
    A_ops.append(A_i)

print(time.now(), "Operators A--", "created:", len(A_ops), "items")

2024-03-02 18:59:43.236837 Operators A-- created: 3 items


In [5]:
# Creating the Hamiltonian
hamiltonian = np.zeros((2**N, 2**N), dtype=float)
for i in range(N):
    # H = sum_i{ epsilon_i A_i } + sum_<ij>{ J A_i A_i+1 }
    hamiltonian += EPSILON * A_ops[i] \
                + J * np.matmul(A_ops[i], A_ops[i+1 if (i+1 < N) else 0])

print(time.now(), "Hamiltonian--", "created")
print(hamiltonian)

2024-03-02 18:59:43.243253 Hamiltonian-- created
[[12.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  6.]]


In [6]:
# Eigenvalues and their corresponding eigenvectors
eig_vals, eig_vecs = np.linalg.eig(hamiltonian)
# The state with the lowest energy
E_0 = min(eig_vals)
PSI_0 = eig_vecs[eig_vals == E_0].transpose()

print(time.now(), "E_0:", min(eig_vals))

M = np.zeros((2**N, 2**N), dtype=float)
for A in A_ops:
    M += A

print(np.matmul(M, PSI_0))

2024-03-02 18:59:43.249982 E_0: -4.0
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [-1.  0.  0.]
 [ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
