In [1]:
import numpy as np
import datetime

In [2]:
N = 3
epsilon = 1
J = 3

pauli_z = np.array([[1, 0],
                    [0, -1]])

In [3]:
def n_identities(n: int):
    """Gives a tensor made out of the tensor product on 'n' identity matrices.

    Args:
        n (int): the number of identity matrices

    Returns:
        np.ndarray: the resultant matrix (tensor)
    """
    return np.identity(2**n) if (n > 0) else 1

$$\mathbf{A}_i = \underbrace{\overbrace{\mathbf{I} \otimes \mathbf{I} \otimes \ldots}^{i - 1\ \text{operators}} \otimes \sigma^z \otimes \overbrace{\ldots \otimes \mathbf{I} \otimes \mathbf{I}}^{N - 1\ \text{operators}}}_{N\ \text{operators}}$$

In [4]:
# A list to store the operators A
A_ops = []
for i in range(1, N+1):
    A_i = np.kron(np.kron(n_identities(i-1), pauli_z), n_identities(N-i))
    A_ops.append(A_i)

A_ops = np.array(A_ops)

$$\mathbf{H} = \epsilon \sum_{i}^{N} \mathbf{A}_i +J \sum_{\left< i j \right>} \mathbf{A}_i \mathbf{A}_{i + 1}$$

In [5]:
# Creating the Hamiltonian
H = np.zeros((2**N, 2**N), dtype=float)
for i in range(N):
    H += epsilon * A_ops[i] + J * np.matmul(A_ops[i], A_ops[i+1 if (i+1 < N) else 0])

print("Hamiltonian =\n", H)

Hamiltonian =
 [[12.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  6.]]


In [6]:
# Eigenvalues and their corresponding eigenvectors
eig_vals, eig_vecs = np.linalg.eig(H)
# The lowest energy
E_0 = min(eig_vals)
# The state with the lowest energy
psi_0 = eig_vecs[eig_vals == E_0].T
psi_0_row, psi_0_col = psi_0.shape
if psi_0_col > 1:
    psi_0 = psi_0[:,0].reshape(-1, 1)
    print("E_0 degeneracy =\n", psi_0_col)

print("E_0 =\n", min(eig_vals))

E_0 degeneracy =
 3
E_0 =
 -4.0


$$\mathbf{M} = \sum_{i = 1}^{N} \mathbf{A}_i, \quad M_0 = \left< \psi_0 \right| \mathbf{M} \left| \psi_0 \right>$$

In [7]:
# Magnetization operator
M_op = A_ops.sum(axis=0)
M = np.matmul(psi_0.conjugate().T, np.matmul(M_op, psi_0))[0,0]

print("M =\n", M)

M =
 -1.0
